query GetChannelConvo($channel:ID!) {
  byId {
    channel(id: $channel) {
      __typename
      ... on TextChannel {
        talk {
          messages(last: 30) @paginate(name: "Channel_Messages", mode: Infinite) {
            edges {
              node {
                id
                content
                createdAt
                reference {
                  id
                  author {
                    id
                    tag
                    displayName
                  }
                  content
                  createdAt
                }
                author {
                  id
                  tag
                  displayName
                }
                recipient {
                  asChannel {
                    identifier
                    name
                    __typename
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
