query GetDM($userId: ID!) {
  conversationDirect(recipient: $userId) {
    messages(last: 20) @paginate(mode: Infinite) {
      edges {
        node {
          id
          content
          createdAt
          author {
            id
            tag
            displayName
          }
          recipient {
            asUser {
              id
              tag
              displayName
            }
          }
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
