query GetDM($userId: ID!) @cache(policy: CacheAndNetwork) {
  conversationDirect(recipient: $userId) {
    messages(last: 20) @paginate(mode: Infinite, name: "Chat_Messages") {
      edges {
        node {
          id
          content
          createdAt
          author {
            id
            tag
            displayName
          }
          reference {
            id
            author {
              id
              tag
              displayName
            }
            content
            createdAt
          }
          recipient {
            asUser {
              id
              tag
              displayName
            }
          }
        }
      }
    }
  }
}
