mutation SendMessage($init:MessageInit!) {
  sendMessage(message: $init) {
    id
    author {
      id
      displayName
    }
    content
    recipient {
      asUser {
        id
        displayName
      }
    }
  }
}
