subscription SentMessages {
  messages {
    id
    author {
      id
      tag
      displayName
    }
    content
    createdAt
    recipient {
      asUser {
        id
        tag
        displayName
      }
      asChannel {
        identifier
        name
        __typename
      }
    }
  }
}
